import { Product } from "./types";

// Product data for frontend display - all functionality is handled by backend
export const mockProducts: Product[] = [
  {
    id: "e1",
    name: "AuraSound Pro Headphones",
    category: "electronics",
    price: 249.99,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
    description: "Premium wireless headphones with adaptive noise cancellation and spatial audio.",
    specs: { "Battery": "40 hours", "Driver": "50mm", "Connectivity": "Bluetooth 5.3", "Weight": "260g" },
    inStock: true,
  },
  {
    id: "e2",
    name: "NovaPad Ultra Tablet",
    category: "electronics",
    price: 599.00,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&q=80",
    description: "12.9\" OLED display tablet with M3 chip, perfect for creative professionals.",
    specs: { "Display": "12.9\" OLED", "Chip": "M3", "Storage": "256GB", "Battery": "12 hours" },
    inStock: true,
  },
  {
    id: "e3",
    name: "PixelLens 4K Camera",
    category: "electronics",
    price: 899.00,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80",
    description: "Mirrorless camera with 4K video, 45MP sensor, and AI autofocus.",
    specs: { "Sensor": "45MP", "Video": "4K 120fps", "ISO": "100-51200", "Weight": "450g" },
    inStock: true,
  },
  {
    id: "c1",
    name: "Cloud Walker Sneakers",
    category: "clothing",
    price: 129.99,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
    description: "Ultralight running sneakers with responsive foam and breathable knit upper.",
    specs: { "Material": "Flyknit", "Sole": "React foam", "Weight": "220g", "Sizes": "6-14" },
    inStock: true,
  },
  {
    id: "c2",
    name: "Arctic Shell Jacket",
    category: "clothing",
    price: 289.00,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&q=80",
    description: "Waterproof insulated jacket for extreme cold with recycled materials.",
    specs: { "Waterproof": "20K mm", "Insulation": "800-fill down", "Weight": "680g", "Temp": "-30°C" },
    inStock: true,
  },
  {
    id: "t1",
    name: "RoboBuilder Kit",
    category: "toys",
    price: 79.99,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1535378620166-273708d44e4c?w=400&q=80",
    description: "STEM robotics kit with 300+ pieces, app-controlled, ages 8+.",
    specs: { "Pieces": "300+", "Ages": "8+", "App": "iOS/Android", "Motors": "3 servo" },
    inStock: true,
  },
  {
    id: "t2",
    name: "Cosmic Explorer Telescope",
    category: "toys",
    price: 159.00,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1532968961962-8a0cb3a2d4f5?w=400&q=80",
    description: "Beginner telescope with smartphone adapter and star-finding app.",
    specs: { "Aperture": "70mm", "Magnification": "150x", "Mount": "AltAz", "Includes": "Phone adapter" },
    inStock: false,
  },
  {
    id: "l1",
    name: "ZenBrew Coffee Maker",
    category: "lifestyle",
    price: 199.00,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",
    description: "Smart pour-over coffee maker with temperature control and scheduling.",
    specs: { "Capacity": "1L", "Temp Range": "85-96°C", "Features": "WiFi, Timer", "Material": "Steel" },
    inStock: true,
  },
  {
    id: "l2",
    name: "LumiScape Smart Lamp",
    category: "lifestyle",
    price: 89.99,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=400&q=80",
    description: "Adaptive desk lamp with circadian rhythm lighting and wireless charging base.",
    specs: { "Lumens": "800", "Color Temp": "2700-6500K", "Features": "Qi charging", "Control": "App/Touch" },
    inStock: true,
  },
];

export const suggestedPrompts = [
  "Show me the best headphones under $300",
  "Compare tablets and cameras for content creation", 
  "I need a gift for an 8-year-old who loves science",
  "What's trending in lifestyle products?",
  "Find me waterproof jackets for winter hiking",
  "Recommend a home office setup under $500",
];